inherit_gem:
  simplycop: .simplycop.yml

AllCops:
  TargetRubyVersion: 2.6
  Rails:
    Enabled: false
  Documentation:
    Enabled: false
Metrics/BlockLength:
  Max: 200
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 25
