name: Ruby CI

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ruby

    strategy:
      matrix:
        ruby-version: [2.6, 2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: run rubocop
      run: bundle exec rubocop
    - name: Run all tests
      run: for file in test/*test.rb; do ruby $file; done
      shell: bash
